apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: nodejs-ns 
spec:
  selector:
    app:  nodejs-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer