apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace:  nodejs-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  nodejs-app
  template:
    metadata:
      labels: 
        app:  nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image:  santana20095/aws-nodejs-app:1.0
        ports:
        - containerPort: 3000